### ISSUE TITLE
R package ncdf4 issues

### ISSUE THREAD

**Issue by kellijohnson** [r4atlantis/atlantisom#1]
We need to include instructions for users on how to install the `ncdf4` package or not include it in our imports. I am on a windows machine 64 bit machine and even if I say build from source the package does not install on my computer. It appears that the package may be an issue for people using 64 bit computers it may be an issue to install because it assumes you have the [ncdf library installed on your computer](http://r.789695.n4.nabble.com/big-difference-between-ncdf-and-RNetCDF-td4676332.html).

**Comment by alketh** [comment]
The package can be installed as "tar.gz" using the option "Package Archive File" in RStudio.Or using install.packages("folder/package.tar.gz", repos = NULL, type = "source").

**Comment by kellijohnson** [comment]
Now using `RNetCDF`
