### ISSUE TITLE
function run_atlantis

### ISSUE THREAD

**Issue by hodgsone** [r4atlantis/atlantisom#15]
Currently being written to call in all of the `load_atlantis_ncdf` and other outputs to create the Rdata product which contains all truth. This function will load in numbers at stage, structN, resN, temperature, diet composition (proportions), diet biomass (using `calc_pred_diet`), call in model info (using `load_meta`), calculate length at stage (using `calc_stage2length`), and also catch inputs, for biomass and numbers -- see issue 'Fishing stage classes' since catch is currently only correct in total biomass per functional group per box, and not per age class.
- [x] finish and upload to Github
- [x] document
- [x] test that it plays nice with the other functions

**Comment by kellijohnson** [comment]
Will need additional work later, but closing this issue as we need to work on other things and it has as much functionality as we currently need.
