### ISSUE TITLE
Loading functions from packages!

### ISSUE THREAD

**Issue by alketh** [r4atlantis/atlantisom#17]
we should always explicitly name the packages the functions origin from to minimize conflicts between package dependencies. E.g. instead of importing functions like "open.nc" use RNetCDF::open.nc instead.

**Comment by kellijohnson** [comment]
@alketh this is great advice. I am going to go through the current functions and make sure this practice is being used and then I will make a note of it in #10 so that we do not forget. I have also started a best practices guide in the [wiki](https://github.com/r4atlantis/atlantisom/wiki/Namespace).

**Comment by kellijohnson** [comment]
@alketh can you make sure the `%>%` thing is properly documented with `@importsFrom` or however we should do it. I am not familiar with the pipes and where they come from otherwise I would.

@slucey can you make sure `data.table` is documented everywhere it should be? Thanks.

**Comment by kellijohnson** [comment]
Eventually I will be removing all references to data.table and arrayhelpers. These two functions make code reading by non users of those packages difficult and if using data.table the package is not CRAN compatible. Otherwise everyone is doing a good job using ::

**Comment by slucey** [comment]
I'm not sure what you mean that using data table will make the package not
CRAN compatible.  There are over 60 packages on CRAN that use data table
already.  I agree that it makes reading the code different but the package
is super powerful and useful.

Sean


Sean M. Lucey
Fisheries Biologist
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by kellijohnson** [comment]
when you run `devtools::check()` you will receive warnings for both subsetting using `data.table` functions or if you use the `subset` function.
