### ISSUE TITLE
function load_atlantis_ncdf

### ISSUE THREAD

**Issue by kellijohnson** [r4atlantis/atlantisom#3]
`load_atlantis_ncdf` is currently written but has some issues:
- [x] relies on `ncdf4` and should instead use 'RNetCDF', referenced in issue #1
- [ ] test that 'load_atlantis_ncdf' can open the new age bin file which is currently relies on new output from Atlantis. the new output is not available yet and thus hard to code for things which you do not know the structure
- [x] rename file/function to 'load_ncdf' because all 'load' functions should have the file they reference after the '_'
- [x] add '@family load functions' to the roxygen documentation

**Comment by kellijohnson** [comment]
@alketh can you provide access to `get_bboxes()`

**Comment by alketh** [comment]
get_bboxes() is hard coded in the current state of my package. As far as I know, currently there is no way to extract the boundary boxes in an automated way. We have to check with Beth to solve this.

**Comment by kellijohnson** [comment]
the hard coded portion in your package: is it just a vector? or what are you passing inside `load_atlantis_nncdf`?

**Comment by alketh** [comment]
The output of get_bboxes() is simply a vector of integers given the id of the boundary boxes. For the CaCu model these are:   0, 54, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88

**Comment by slucey** [comment]
We can make it a simple argument for the time being.

Sean


Sean M. Lucey
Fisheries Biologist
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by kellijohnson** [comment]
i almost have a function, `get_boundary` to get it from the `.bgm` file, it is currently picking up every boundary box except 1, box 54, which is an island.

**Comment by alketh** [comment]
Treating islands as boundary boxes should work fine.

**Comment by kellijohnson** [comment]
I cannot pick up the island with my function though. I will have to ask 
Beth, Bec, or Isaac on how to find islands, maybe something regarding if 
land is included and if it is not assume all boxes on land are boundary?

**Comment by alketh** [comment]
Sorry guys, I am having a hard time to getting used to RNetCDF due to the complete different structure of the loaded nc-files. How can I extract the number if dimensions of a variable in the ncfile?

**Comment by kellijohnson** [comment]
`RNetCDF::dim.inq.nc(at_out, 0)$length` will give you the dimensions of 
timesteps.
In the command line run:
`git fetch`
`git rebase origin/master`
to get my latest changes, as I already fixed a few things.

**Comment by kellijohnson** [comment]
@alketh what file are you referring to when you get the biomass pools? The CaCur model does not have an `init...nc` file.

**Comment by alketh** [comment]
The file is named "DIVCalCurrentV3_Biol.nc". Isaac didn't supply it with his model-folder. I make sure that everybody in here gets a copy of it.

**Comment by kellijohnson** [comment]
great

**Comment by alketh** [comment]
I just checked the new version of the load_nc function. The code looks great. However, I would like to give a catious remark regarding the file structure of different atlantis models. We have to be cautious when we supply a "global" direction ("dir") of the input files. This does only work if all files are read in from one location. Unfortunately, this is not the case for multiple atlantis models. Many models have a main folder and output folder. Therefore I highly suggest to provide the files as full folder/filename string (similar to the "con" parameter used in various R-functions).

**Comment by hodgsone** [comment]
Hey all, 

I am working on the calc_stage2age and in order to do that I needed an example file -- when I run the load_nc file the column of time just outputs zeros no matter what run's nc file I am pulling in. Have others found this?

**Comment by alketh** [comment]
Hey,

I just read in "ResN" from the general output-file using load_nc. All 
time steps (from 0 to 63) were present in the resulting dataframe.

Am 08.12.2015 um 15:05 schrieb hodgsone:
>
> Hey all,
>
> I am working on the calc_stage2age and in order to do that I needed an 
> example file -- when I run the load_nc file the column of time just 
> outputs zeros no matter what run's nc file I am pulling in. Have 
> others found this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/r4atlantis/atlantisom/issues/3#issuecomment-163074286>.
>

-- 
<°)))>< ><(((°> <°)))>< ><(((°> <°)))>< ><(((°>

Alexander Keth
Institute for Hydrobiology and Fisheries Science
University of Hamburg
Olbersweg 24
22767 Hamburg
Germany
Tel.: +49 (0)40 428 38 6708
Fax:  +49 (0)40 428 38 6618

<°)))>< ><(((°> <°)))>< ><(((°> <°)))>< ><(((°>

**Comment by slucey** [comment]
I have some sample data we can use but GitHub won't let me send it through
this e-mail string.  Send me your e-mail address and I'll send it to you.

Sean


Sean M. Lucey
Fisheries Biologist
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by hodgsone** [comment]
Thanks Sean -- my email is hodgsone@uw.edu, but I also have sample files so I am not sure that is the issue -- these are outputs from old runs I have done and have multiple time steps. I am not sure why it does not work for mine. I can try again

**Comment by kellijohnson** [comment]
`load_nc` works great.
