### ISSUE TITLE
links to create_fishery_data.r

### ISSUE THREAD

**Issue by andybeet** [r4atlantis/atlantisom#40]
There are links in several of the help functions to a function called "create_fishery_data" which does not seem to be present in the package. Maybe these links need to be changed to an alternative function name or removed

**Comment by kellijohnson-NOAA** [comment]
9c5102e8bbbc1e597b5156c2ecfae36771bff8e3 changed it to `create_fishery_subset`

**Comment by sgaichas** [comment]
thanks @andybeet and @kellijohnson-NOAA. I need to do documentation cleanup; next task after the annage branch comes in.

**Comment by sgaichas** [comment]
documentation should be updated now https://github.com/r4atlantis/atlantisom/commit/4c4aedb713f44b8d2bf7e53ba464bd07ce166f42
