### ISSUE TITLE
read_savedfisheries() function couldn't been used

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [r4atlantis/atlantisom#51]
I was using read_savedfisheries() to load catch data and got the error message below.
```r
truecatchbio <- read_savedfisheries(d.name, "Catch") 
Error in read_savedfisheries(d.name, "Catch") : 
  could not find function "read_savedfisheries"
```

It seems that read_savedfisheries() has not been exported to the [NAMESPACE](https://github.com/r4atlantis/atlantisom/blob/master/NAMESPACE). The function works after I update the NAMESPACE with `devtools::document()` locally.

**Comment by sgaichas** [comment]
thank you for pointing this out! should be fixed with 500614ba5374730883cecf46cf1947f97b3232be
