### ISSUE TITLE
function create_survey

### ISSUE THREAD

**Issue by kellijohnson** [r4atlantis/atlantisom#6]
The function `create_survey` is being created.
- [x] upload to github
- [x] document
- [x] test that it plays nice with the other functions

**Comment by allanhicks** [comment]
Uploaded to Github and works with a simple example.

**Comment by allanhicks** [comment]
I'm closing this issue for now because it takes output from run_atlantis and passes it right into sample_ages.  The function still needs work (e.g., error checking), but it plays nicely for now.
